server:
  port: 8080
spring:
  freemarker:
    enabled: true
    cache: true
    charset: UTF-8
    suffix: .ftl
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/mt4_gold?useSSL=false&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
blog:
  email: juniterr@outlook.com